coverage:
  status:
    patch:
      default:
        target: auto
        # this allows a 10% drop from the previous base commit coverage
        threshold: 10%
    project:
      default:
        target: auto
        # this allows a 10% drop from the previous base commit coverage
        threshold: 10%